[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "fgread"
author = "FASTGenomics Team"
author-email = "contact@fastgenomics.org"
description-file = 'README.md'
home-page = 'https://github.com/fastgenomics/jupyter-fgread-py'
requires-python = '~=3.6'
requires=[
    "anndata >= 0.6",
    'get_version (~=2.0.6)',
    "tables >= 3.4",
    "loompy >= 2.0.12"
]


[tool.flit.metadata.requires-extra]
test = [
    "pytest >= 4"
]
