[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "readfg"
author = "FASTGenomics Team"
author-email = "contact@fastgenomics.org"
description-file = 'README.md'
home-page = 'https://github.com/fastgenomics/jupyter-fgread-py'
requires-python = '~=3.6'
requires=[
    "scanpy",
    'get_version (~=2.0.6)'
]
